name: flow-api
region: nyc
services:
- environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: Flow-Stethoscope/Flow-Backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: flow-api
  routes:
  - path: /
  run_command: flask run --host=0.0.0.0 --port=8080
  source_dir: /
